Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2018-07, with the labels that each got.

#370 feat(scripts): add boilerplate to detect missing migrations
  lib/db/patch.js
  lib/db/schema/patch-082-083.sql
  lib/db/schema/patch-083-082.sql
  scripts/migration.sh
  test/local/mysql_tests.js
Labels: waffle:active

#372 refactor(recovery): Use base32 for recovery code generation
  config/config.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/random.js
  lib/db/util.js
  test/lib/utils.js
  test/local/random.js
Labels: waffle:active

#374 feat(recovery): update account recovery GET/DEL to not accept recoveryKeyId
  db-server/index.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  docs/API.md
  docs/DB_API.md
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-083-084.sql
  lib/db/schema/patch-084-083.sql
Labels: waffle:review

#375 feat(ci): update to circle 2
  .circleci/config.yml
  circle.yml
Labels: waffle:active

#377 fix(tests): move local utils tests so they get run by npm t
  test/local/utils.js
Labels: train-117, waffle:review

#379 Release v1.117.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active
