Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2018-09, with the labels that each got.

#395 fix(recovery): hash recovery key id
  db-server/index.js
  db-server/lib/error.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  docs/API.md
  docs/DB_API.md
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-085-086.sql
  lib/db/schema/patch-086-085.sql
  lib/db/util.js
Labels: train-120, waffle:review

#396 Release v1.120.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#398 Release v1.121.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#399 feat(account): add `profileChangedAt` property to account table
  db-server/test/backend/db_tests.js
  docs/DB_API.md
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-086-087.sql
  lib/db/schema/patch-087-086.sql
Labels: train-122, waffle:review
