Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2018-10, with the labels that each got.

#401 Release v1.122.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#402 fix(account): delete recovery codes/keys, security events on account delete
  db-server/test/backend/db_tests.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-087-088.sql
  lib/db/schema/patch-088-087.sql
  package.json
Labels: train-123, waffle:review

#404 chore(deps): Update deps to fix security warnings, remove nsp
  .travis.yml
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#408 fix(mem): ensure emailBounces are stored most-recent first
  db-server/test/backend/db_tests.js
  lib/db/mem.js
Labels: waffle:review

#406 fix(performance): Add index for scanning signinCodes by uid.
  lib/db/patch.js
  lib/db/schema/patch-088-089.sql
  lib/db/schema/patch-089-088.sql
Labels: waffle:active

#409 Release v1.123.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#410 fix(account): update stored procedures to be more replication friendly
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-086-087.sql
  lib/db/schema/patch-087-086.sql
Labels: waffle:review

#412 Train 122 lift 121
  CHANGELOG.md
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-087-088.sql
  lib/db/schema/patch-088-087.sql
Labels: waffle:active

#416 Master uplift train 123 v2
  CHANGELOG.md
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-089-090.sql
  lib/db/schema/patch-090-089.sql
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#417 Train 123 rollback profilechangedat
  db-server/test/backend/db_tests.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-090-091.sql
  lib/db/schema/patch-091-090.sql
Labels: waffle:active

#418 Uplift train 123
  CHANGELOG.md
  db-server/test/backend/db_tests.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-090-091.sql
  lib/db/schema/patch-091-090.sql
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#421 fix(accountRecord): Rollback `accountRecord_4` due to unexplained performance issues
  lib/db/mysql.js
  lib/db/schema/patch-091-090.sql
Labels: waffle:active

#424 Uplift train-123 point-releases to master.
  CHANGELOG.md
  lib/db/mysql.js
  lib/db/schema/patch-091-090.sql
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#426 Merge train-124 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:review
