Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2018-08, with the labels that each got.

#381 fix(restify): set keepAliveTimeout correctly on api.server object
  db-server/index.js
Labels: waffle:active

#383 chore(db): stop calling the upsertAvailableCommands procedure
  db-server/test/backend/db_tests.js
  lib/db/mysql.js
Labels: waffle:active

#385 Merge train-118 into master
  CHANGELOG.md
  db-server/test/backend/db_tests.js
  lib/db/mysql.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#386 chore(db): ensure mem db behaves like mysql db
  lib/db/mem.js
Labels: shipit, train-119, waffle:review

#388 Release v1.119.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#389 fix(devices): Reinstate device commands, with performance fixes.
  db-server/test/backend/db_tests.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-084-085.sql
  lib/db/schema/patch-085-084.sql
Labels: waffle:active

#390 Release v1.119.1
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#391 chore(docs): update mysql docs
  README.md
Labels: waffle:review

#394 fix(scripts): remove nonsense (but harmless) comparison of bool to -1
  scripts/analyze-mx-stats.js
Labels: waffle:review
