Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2018-03, with the labels that each got.

#314 Fixes issue #290 Remove database configuration option, hardcode 'fxa' 
  bin/db_patcher.js
  config/config.js
  lib/constants.js
  lib/db/mysql.js
  test/local/constants_test.js
  test/local/metrics_tests.js
Labels: waffle:active

#315 Fixes issue #311 Use email buffer for DEL ‘/email/:email’ route
  db-server/index.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  db-server/test/fake.js
  lib/db/mem.js
  lib/db/mysql.js
  scripts/populate-session-tokens.js
  test/local/metrics_tests.js
Labels: waffle:review

#317 Fixes issue #316 Convert remaining '= Buffer(stuff)' to 'Buffer.from(…
  db-server/test/backend/db_tests.js
Labels: waffle:active

#320 feat(devices): Devices capabilities
  db-server/lib/error.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  db-server/test/fake.js
  docs/API.md
  docs/DB_API.md
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-073-074.sql
  lib/db/schema/patch-074-073.sql
  lib/db/util.js
Labels: waffle:review

#324 feat(node): update to node v6.13.1
  Dockerfile-build
Labels: waffle:active

#323 chore(api): #318 remove bufferization from db layer
  db-server/index.js
  db-server/lib/bufferize.js
  db-server/test/backend/db_tests.js
  db-server/test/local/bufferize.js
  lib/db/mem.js
  lib/db/mysql.js
Labels: waffle:review

#319 feat(totp): initial recovery codes
  db-server/index.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  docs/API.md
  docs/DB_API.md
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-074-075.sql
  lib/db/schema/patch-075-074.sql
  lib/db/util.js
Labels: shipit, train-108, waffle:review

#325 fix(test): #321 Correct promises error handling
  db-server/test/backend/remote.js
Labels: waffle:active

#329 fix(verify): `verifyTokenWithMethod` should update already verified session status
  db-server/test/backend/db_tests.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-075-076.sql
  lib/db/schema/patch-076-075.sql
Labels: WIP, waffle:active

#327 feat(mysql): #277 STRICT_ALL_TABLES required sql mode support
  lib/db/mysql.js
  test/local/mysql_tests.js
Labels: waffle:active

#326 fix(codes): drop all codes when one is consumed
  db-server/test/backend/db_tests.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-076-077.sql
  lib/db/schema/patch-077-076.sql
Labels: train-109, waffle:review

#330 fix(unblock): delete unblock codes only when successfully consumed code
  db-server/test/backend/db_tests.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-077-078.sql
  lib/db/schema/patch-078-077.sql
Labels: waffle:active

#332 fix(node): Use Node.js v6.14.0
  Dockerfile-build
Labels: waffle:active
