Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2018-11, with the labels that each got.

#425 fix(scripts): stop the explain script tripping over git grep colours
  scripts/explain-warn.js
Labels: train-125, waffle:review

#429 fix(package): update deps
  npm-shrinkwrap.json
  package.json
Labels: shipit, train-124, waffle:review

#431 chore(db): use mariadb-friendly drop index syntax
  lib/db/schema/patch-035-036.sql
  lib/db/schema/patch-038-039.sql
Labels: train-125, waffle:review

#419 feat(scripts): add ROW_COUNT() checks to the procedure-linting script
  .procedure-lint-ignore
  .travis.yml
  package.json
  scripts/procedure-lint.js
Labels: train-125, waffle:review

#437 Release v1.125.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#439 fix(tests): Don't put binary data into fake email addresses.
  db-server/test/fake.js
Labels: waffle:active

#441 fix(account): don't use `LOWER(uid)` in account query, update `accountRecord`
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-091-092.sql
  lib/db/schema/patch-092-091.sql
Labels: train-127, waffle:review

#442 Release v1.126.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#443 feat(scripts): a bunch of changes to the lint script
  .migration-lint-ignore.json
  .procedure-lint-ignore
  .travis.yml
  package.json
  scripts/migration-lint.js
Labels: waffle:review
