Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2018-04, with the labels that each got.

#334 feat(mysql): Add config option for REQUIRED_SQL_MODES.
  config/config.js
  lib/db/mysql.js
  test/local/mysql_tests.js
Labels: shipit, train-109, waffle:review

#335 fix(devices): Rename pushbox capability to messages
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  db-server/test/fake.js
  docs/API.md
  lib/db/util.js
Labels: waffle:active

#333 fix(codes): update to latest recovery codes requirements
  config/config.js
  db-server/test/backend/db_tests.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-078-079.sql
  lib/db/schema/patch-079-078.sql
  lib/db/util.js
  npm-shrinkwrap.json
  package.json
  test/lib/utils.js
Labels: train-110, waffle:review

#337 fix(codes): remove current recovery codes before applying migration 79
  lib/db/schema/patch-078-079.sql
Labels: WIP, train-110, waffle:active

#339 fix(tests): increase timeout on recovery code tests
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
Labels: waffle:review

#341 feat(node): update to node 8
  .travis.yml
  Dockerfile-build
Labels: waffle:active

#344 fix(npm): update shrinkwrap to npm 5.8
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#342 refactor(db): Fixes #340 Remove column createdAt on recoveryCode table
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-079-080.sql
  lib/db/schema/patch-080-079.sql
Labels: waffle:active
