Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2018-12, with the labels that each got.

#446 Release v1.127.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#445 fix(query): remove `ROW_COUNT()` from remaining procedures
  db-server/lib/error.js
  db-server/test/backend/db_tests.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-092-093.sql
  lib/db/schema/patch-093-092.sql
Labels: waffle:review

#450 feat(npm): update shrink script
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#468 fix(query): update set primary email query to not check if email is verified
  db-server/test/backend/db_tests.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-093-094.sql
  lib/db/schema/patch-094-093.sql
Labels: train-128, waffle:active
