Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2018-05, with the labels that each got.

#347 Update newrelic version
  .nsprc
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#350 feat(changelog): Add an "acknowledgements" section to some changelog entries.
  CHANGELOG.md
Labels: waffle:active

#351 fix(deps): update restify and mysql
  .nsprc
  db-server/index.js
  db-server/lib/safeJsonFormatter.js
  db-server/test/client-then.js
  db-server/test/local/safeJsonFormatter.js
  npm-shrinkwrap.json
  package.json
Labels: train-112, waffle:review

#352 fix(restify): set a sane max param length value for restify
  db-server/index.js
Labels: waffle:review

#357 feat(recovery): Add initial account recovery key support
  db-server/index.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  docs/API.md
  docs/DB_API.md
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-080-081.sql
  lib/db/schema/patch-081-080.sql
  npm-shrinkwrap.json
Labels: train-113, waffle:review

#354 Let devices register "available commands" with associated metadata.
  db-server/index.js
  db-server/lib/error.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-081-082.sql
  lib/db/schema/patch-082-081.sql
  lib/db/util.js
  test/lib/utils.js
  test/local/metrics_tests.js
Labels: waffle:review

#360 revert(devices): Revert "available commands" for train-113.
  db-server/index.js
  db-server/lib/error.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-081-082.sql
  lib/db/schema/patch-082-081.sql
  lib/db/util.js
  test/lib/utils.js
  test/local/metrics_tests.js
Labels: waffle:active

#361 feat(devices): Allow devices to register "available commands". (#354); r=philbooth,eoger
  db-server/index.js
  db-server/lib/error.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-081-082.sql
  lib/db/schema/patch-082-081.sql
  lib/db/util.js
  test/lib/utils.js
  test/local/metrics_tests.js
Labels: waffle:active
