Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2019-03, with the labels that each got.

#484 chore(routes): Remove last vestiges of `sessionWithDevice` route.
  db-server/index.js
  db-server/test/backend/remote.js
  docs/API.md
Labels: shipit, train-132, waffle:review

#482 feat(account): Add `profileChangedAt` and `keysChangedAt` columns
  db-server/test/backend/db_tests.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-094-095.sql
  lib/db/schema/patch-095-094.sql
Labels: shipit

#486 Release v1.132.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#492 chore(devices): Add explicit deletes to replace `ON DELETE CASCADE`.
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-095-096.sql
  lib/db/schema/patch-096-095.sql
Labels: train-133, waffle:review

#493 Merge train-133 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: train-133, waffle:review

#483 feat(devices): Add ability to associate a device record with a refesh token
  db-server/index.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  db-server/test/fake.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-096-097.sql
  lib/db/schema/patch-097-096.sql
Labels: P1, train-133, waffle:active

#494 Release v1.133.1
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#495 Uplift Train 133 to master
  CHANGELOG.md
  db-server/index.js
  db-server/test/backend/db_tests.js
  db-server/test/backend/remote.js
  db-server/test/fake.js
  lib/db/mem.js
  lib/db/mysql.js
  lib/db/patch.js
  lib/db/schema/patch-096-097.sql
  lib/db/schema/patch-097-096.sql
  npm-shrinkwrap.json
  package.json
Labels: waffle:active
