Repository mozilla/fxa-auth-db-mysql, pull requests merged in 2019-02, with the labels that each got.

#473 fix(tests): pass tests in node 10
  .travis.yml
  lib/db/util.js
  npm-shrinkwrap.json
  package.json
Labels: train-130, waffle:review

#474 Release v1.130.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#475 test(demo): set up triggers like pt-osc and check
  scripts/create-triggers-accounts.sh
  scripts/create-triggers-accounts.sql
  scripts/union-compare-two-tables.sql
Labels: P3, train-131, waffle:review

#477 chore(deploy): upgrade to node 10
  .circleci/config.yml
  .travis.yml
  Dockerfile-build
  npm-shrinkwrap.json
  package.json
Labels: train-132, waffle:review
